cnpmjs:
  build: .
  ports:
    - "7001:7001"
    - "7002:7002"
  links:
    - mysql
  # command: node --harmony /opt/cnpmjs/dispatch.js        
mysql:
  image: tutum/mysql
  environment:
    MYSQL_USER: "test"
    MYSQL_PASS: "testcnpmjs"
    ON_CREATE_DB: "cnpmjs_test"
    STARTUP_SQL: "/opt/cnpmjs/docs/db.sql"
  ports:
    - "3307:3306"
  volumes_from:
    - data

data:
   image: busybox
   volumes:
     - ./data/mysql:/var/lib/mysql
     - ./docs/db.sql:/opt/cnpmjs/docs/db.sql